version: '3.7'

services:
  nginx:
    build:
      context: .
      target: symfony_nginx_prod
    container_name: symfony_nginx
    mem_limit: 128M
    restart: on-failure:3
    networks:
      - symfony
    depends_on:
      - php
    ports:
      - 127.0.0.1:8101:80

  php:
    build:
      context: .
      target: symfony_php_prod
    container_name: symfony_php
    restart: on-failure:3
    environment:
      APP_ENV: prod
      DATABASE_URL: "mysql://symfony:symfony@mysql:3306/symfony?serverVersion=8.0"
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 0.3
    networks:
      - symfony
    volumes:
      - logs:/app/var/log

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure:3
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    networks:
      - symfony
    volumes:
      - db:/var/lib/mysql

volumes:
  logs:
    name: symfony_logs
  db:
    name: symfony_db

networks:
  symfony:
    name: symfony
