version: '3.7'

services:
  nginx:
    build:
      context: .
      target: symfony_nginx_dev
    restart: on-failure
    depends_on:
      - php
    ports:
      - "8001:80"
    volumes:
      - .:/app

  php:
    build:
      context: .
      target: symfony_php_dev
    restart: on-failure
    volumes:
      - .:/app
